# .github/workflows/crawl.yml

on:
  schedule:
    - cron: '0 2 * * *' 

jobs:

  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests notion-py
        
    - name: Run main script
       run: python main.py
