# .github/workflows/crawl.yml 

on:
  schedule: 
    - cron: '*/5 * * * *'
 
jobs:

  crawl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        pip install requests notion-py
    
    - name: Run main script
      run: python main.py
